layout_spectrum: 0.08216969
color:
  saturation: 0.8759398
  brandStrength: 1
  lightness: 0.5891514
  brandColors:
    - '#D8CEBD'
    - '#28150E'
    - '#A4763A'
    - '#D8BB87'
    - '#546D65'
  rhythmicContrast: 0.7175972
typography_spectrum: 0.8952738
name: "Gavin's test site"
