name: "Gavin's test site"
favicon: null
layout_spectrum: 0.08216969
typography_spectrum: 0.83441
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8CEBD'
    - '#28150E'
    - '#A4763A'
    - '#D8BB87'
    - '#546D65'
  brandStrength: 1
  lightness: 0.5891514
  saturation: 0.8759398
  rhythmicContrast: 0.7175972
purpose: []
